name: Node.js Testing

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        node-version: ['16.x', '18.x']
        mongodb-version: ['6.0']

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}      
    - name: Install MongoDB
      uses: supercharge/mongodb-github-action@v1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test